apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-violin
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-violin
  template:
    metadata:
      labels:
        app: go-violin
    spec:
      containers:
      - name: go-violin
        image: ahmedshakshak/go-violin
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: go-violin
  labels:
    app: go-violin
spec:
  selector:
    app: go-violin
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  